name: to_do_list
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.11.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  leak_tracker: ^11.0.1
  leak_tracker_flutter_testing: ^3.0.0
  leak_tracker_testing: ^3.0.2
  test_api: ^0.7.6
  vm_service: ^15.0.2

